Update

diff --git a/.github/workflows/release-fake-one.yml b/.github/workflows/release-fake-one.yml
--- a/.github/workflows/release-fake-one.yml
+++ b/.github/workflows/release-fake-one.yml
@@ -94,6 +94,7 @@ jobs:
         elif [[ ${{ inputs.distro }} == debian && ${{ inputs.arch }} == x64 ]]; then
           TOOLSP=tsduck_$V.debian13_amd64.deb
           DEVP=tsduck-dev_$V.debian13_amd64.deb
+          exit 1 #@@@ simulate failure
         elif [[ ${{ inputs.distro }} == debian && ${{ inputs.arch }} == arm64 ]]; then
           TOOLSP=tsduck_$V.debian13_arm64.deb
           DEVP=tsduck-dev_$V.debian13_arm64.deb
