Update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,11 +18,17 @@ name: Release
 on:
   workflow_dispatch:
     inputs:
-      create_release:
+      release_type:
         type: boolean
         description: 'Create release after build'
         required: true
-        default: false
+        default: 'none'
+        options:
+        - none
+        - update-last
+        - draft
+        - pre-release
+        - official
       build_x64:
         type: boolean
         description: 'Build Intel x64 packages'
@@ -159,6 +165,7 @@ jobs:
     - name: List installers
       run: |
         Get-ChildItem pkg\installers
+        Write-Output ""
         if ($${{ inputs.build_x64 }}) {
             $TSW64 = (Get-ChildItem pkg\installers\TSDuck-Win64-*.exe).Name
             $TSW64P = (Get-ChildItem pkg\installers\TSDuck-Win64-*.exe).Name
@@ -206,7 +213,7 @@ jobs:
 
   release:
     name: Create the release
-    if: ${{ inputs.create_release }}
+    if: ${{ inputs.release_type != 'none' }}
     needs: [linux, windows]
     runs-on: ubuntu-latest
     permissions:
@@ -223,19 +230,33 @@ jobs:
     - name: Extract artifacts
       run: |
         cd pkg/installers
-        for f in tsduck-*-x64 tsduck-*-arm64; do
-            if [[ -d $f ]]; then
-                mv $f/* .
-                rmdir $f
-            else
-                mv $f $f.zip
-                unzip $f.zip
-            fi
-        done
+        if ${{ inputs.build_x64 }}; then
+            for f in tsduck-*-x64; do
+                if [[ -d $f ]]; then
+                    mv $f/* .
+                    rmdir $f
+                fi
+            done
+        fi
+        if ${{ inputs.build_arm64 }}; then
+            for tsduck-*-arm64; do
+                if [[ -d $f ]]; then
+                    mv $f/* .
+                    rmdir $f
+                fi
+            done
+        fi
         ls -lR
     - name: Create the release
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         echo "Creating release in repository ${{ github.repository }}"
-        pkg/github/release.py --create --missing --draft --repo ${{ github.repository }}
+        case ${{ inputs.release_type }} in
+            update-last) opt="--update" ;;
+            draft)       opt="--create --missing --draft" ;;
+            pre-release) opt="--create --missing --pre" ;;
+            official)    opt="--create --missing" ;;
+            *) echo "Invalid release_type: ${{ inputs.release_type }}"; exit 1 ;;
+        esac
+        pkg/github/release.py --repo ${{ github.repository }} $opt
